import fs from 'fs';

const existing = JSON.parse(fs.readFileSync('data/lightbag-gear-db.json', 'utf8'));
const existingIds = new Set(existing.map((i) => i.id));

const batch2 = [
  // --- TRIPODS ---
  {
    id: 'lb-tripod-manfrotto-element-mii',
    category: 'tripod',
    subcategory: 'Compact Aluminum Tripod',
    brand: 'Manfrotto',
    model: 'Element MII Aluminum',
    keySpecs: {
      material: 'Aluminum',
      maxHeight: '160 cm',
      foldedLength: '42.5 cm',
      maxLoad: '8 kg',
      head: 'Aluminum Center Ball Head with independent pan lock',
    },
    weight: '1.55 kg',
    officialUrl: 'https://www.manfrotto.com/global-en/element-mii-aluminum-black-tripod-mkeltmii4bk-bh/',
    source: 'lightbag-db',
  },
  {
    id: 'lb-tripod-manfrotto-pixi-mini',
    category: 'tripod',
    subcategory: 'Mini Tabletop Tripod',
    brand: 'Manfrotto',
    model: 'PIXI Mini Tripod',
    keySpecs: {
      material: 'Adapto Polymer & Stainless Steel',
      maxHeight: '13.5 cm',
      foldedLength: '18.5 cm',
      maxLoad: '1 kg',
      locking: 'Push-button ball head lock mechanism',
    },
    weight: '190 g',
    officialUrl: 'https://www.manfrotto.com/global-en/pixi-mini-tripod-black-mtpixi-b/',
    source: 'lightbag-db',
  },
  {
    id: 'lb-tripod-manfrotto-xpro-carbon-monopod',
    category: 'tripod',
    subcategory: 'Carbon Fiber Monopod',
    brand: 'Manfrotto',
    model: 'XPRO 4-Section Carbon Monopod',
    keySpecs: {
      material: '100% Carbon Fiber Tubes',
      maxHeight: '164 cm',
      foldedLength: '52 cm',
      maxLoad: '20 kg',
      locking: 'Quick Power Lock (QPL) levers',
    },
    weight: '600 g',
    officialUrl: 'https://www.manfrotto.com/global-en/xpro-monopod-carbon-fibre-4-sections-mpmxproc4/',
    source: 'lightbag-db',
  },
  {
    id: 'lb-tripod-benro-mach3-9x-carbon',
    category: 'tripod',
    subcategory: 'Studio Carbon Tripod',
    brand: 'Benro',
    model: 'Mach3 9X Carbon Fiber (TMA37C)',
    keySpecs: {
      material: '9x Carbon Fiber Weave',
      maxHeight: '161.5 cm',
      foldedLength: '62.5 cm',
      maxLoad: '16 kg',
      locking: 'Dust-resistant twist leg locks',
    },
    weight: '2.06 kg',
    officialUrl: 'https://benroeu.com/benro-mach3-tripods/',
    source: 'lightbag-db',
  },
  {
    id: 'lb-tripod-benro-bv6-video-kit',
    category: 'tripod',
    subcategory: 'Video Fluid Head Tripod',
    brand: 'Benro',
    model: 'BV6 Video Tripod Kit',
    keySpecs: {
      material: 'Aluminum Dual-Tube with 75mm Bowl',
      maxHeight: '160 cm',
      maxLoad: '6 kg',
      counterbalance: '8-Step Counterbalance system',
      spreader: 'Mid-level spreader with rubber feet',
    },
    weight: '5.6 kg',
    officialUrl: 'https://benroeu.com/benro-bv-video-tripod-kits/',
    source: 'lightbag-db',
  },
  {
    id: 'lb-tripod-leofoto-ranger-ls-324c',
    category: 'tripod',
    subcategory: 'Professional Carbon Tripod',
    brand: 'Leofoto',
    model: 'Ranger LS-324C + LH-40 Ball Head',
    keySpecs: {
      material: '10x Toray Carbon Fiber',
      maxHeight: '139 cm (170 cm with column)',
      foldedLength: '48 cm',
      maxLoad: '15 kg',
      head: 'LH-40 Low Profile Center Ball Head (40mm ball)',
    },
    weight: '1.93 kg',
    officialUrl: 'https://leofoto.com/products_detail.php?id=324',
    source: 'lightbag-db',
  },
  {
    id: 'lb-tripod-smallrig-ct180-video',
    category: 'tripod',
    subcategory: 'Lightweight Video Tripod',
    brand: 'SmallRig',
    model: 'CT180 Lightweight Video Tripod',
    keySpecs: {
      material: 'Aluminum Alloy',
      maxHeight: '180 cm',
      foldedLength: '42 cm',
      maxLoad: '3 kg (Head) / 15 kg (Legs)',
      head: 'Mini Fluid Head with 360° pan and +90°/-55° tilt',
    },
    weight: '1.68 kg',
    officialUrl: 'https://www.smallrig.com/SmallRig-CT180-Video-Tripod-3930.html',
    source: 'lightbag-db',
  },
  {
    id: 'lb-tripod-gitzo-mountaineer-series-2',
    category: 'tripod',
    subcategory: 'All-Round Carbon Tripod',
    brand: 'Gitzo',
    model: 'Mountaineer Series 2 Carbon (GT2542)',
    keySpecs: {
      material: 'Carbon eXact Tubing',
      maxHeight: '167 cm',
      foldedLength: '54 cm',
      maxLoad: '18 kg',
      centerColumn: 'G-Lock Ultra & Ground Level Set mechanism',
    },
    weight: '1.68 kg',
    officialUrl: 'https://www.gitzo.com/global-en/mountaineer-tripod-series-2-carbon-4-sections-gt2542/',
    source: 'lightbag-db',
  },
  {
    id: 'lb-tripod-ulanzi-tt09-video-fast-lock',
    category: 'tripod',
    subcategory: 'Fast Lock Video Tripod',
    brand: 'Ulanzi',
    model: 'TT09 Video Fast Lock Carbon Tripod',
    keySpecs: {
      material: 'Carbon Fiber with Quick-Deployment Lever',
      maxHeight: '142 cm',
      foldedLength: '45 cm',
      maxLoad: '5 kg (Ball Head)',
      head: 'Integrated Panoramic Leveling Bowl Head with Arca & F38 mount',
    },
    weight: '1.5 kg',
    officialUrl: 'https://www.ulanzi.com/products/ulanzi-tt09-video-fast-lock-tripod',
    source: 'lightbag-db',
  },

  // --- GIMBALS ---
  {
    id: 'lb-gimbal-dji-rsc-2',
    category: 'gimbal',
    subcategory: 'Foldable 3-Axis Gimbal',
    brand: 'DJI',
    model: 'DJI RSC 2',
    keySpecs: {
      testedPayload: '3.0 kg (6.6 lbs)',
      foldingDesign: 'Foldable design with 6 configurations',
      screen: '1.0" Built-in OLED Screen',
      batteryLife: 'Up to 14 hours',
    },
    weight: '1.2 kg',
    officialUrl: 'https://www.dji.com/rsc-2',
    source: 'lightbag-db',
  },
  {
    id: 'lb-gimbal-dji-ronin-4d-6k',
    category: 'gimbal',
    subcategory: '4-Axis Cinema Camera System',
    brand: 'DJI',
    model: 'DJI Ronin 4D 6K',
    keySpecs: {
      stabilization: '4-Axis Active Stabilization (Z-Axis vertical damping)',
      sensor: 'Full-Frame Zenmuse X9-6K (ProRes RAW, 6K/60fps, 4K/120fps)',
      lidar: 'LiDAR Waveform Focus System (43,200 ranging points)',
      transmission: 'Integrated 20,000 ft O3 Pro Video Transmission',
    },
    weight: '4.67 kg (Combination)',
    officialUrl: 'https://www.dji.com/ronin-4d',
    source: 'lightbag-db',
  },
  {
    id: 'lb-gimbal-dji-osmo-mobile-se',
    category: 'gimbal',
    subcategory: 'Foldable Phone Gimbal',
    brand: 'DJI',
    model: 'DJI Osmo Mobile SE',
    keySpecs: {
      compatibility: 'Magnetic Phone Clamp for iPhone / Android',
      tracking: 'ActiveTrack 5.0 subject tracking',
      statusPanel: 'Status Panel for battery level & gimbal mode',
      batteryLife: 'Up to 8 hours',
    },
    weight: '352 g',
    officialUrl: 'https://www.dji.com/osmo-mobile-se',
    source: 'lightbag-db',
  },
  {
    id: 'lb-gimbal-zhiyun-crane-3s',
    category: 'gimbal',
    subcategory: 'Heavy Cinema Camera Gimbal',
    brand: 'Zhiyun',
    model: 'CRANE 3S',
    keySpecs: {
      testedPayload: '6.5 kg (Supports Canon C300, Sony FX9, RED, ARRI)',
      extendableAxis: 'Detachable extension module on roll axis for cine rigs',
      handleOptions: 'TransMount SmartSling & EasySling handles',
      dcIn: 'DC-in port for TransMount PowerPlus battery pack',
    },
    weight: '2.47 kg',
    officialUrl: 'https://www.zhiyun-tech.com/en/product/detail/103',
    source: 'lightbag-db',
  },
  {
    id: 'lb-gimbal-zhiyun-weebill-2',
    category: 'gimbal',
    subcategory: 'Touchscreen Camera Gimbal',
    brand: 'Zhiyun',
    model: 'WEEBILL 2',
    keySpecs: {
      screen: '2.88" Flip-out Full-Color Touchscreen',
      chipset: 'Infineon sensor vector-splitting chip',
      testedPayload: '3.3 kg',
      batteryLife: 'Up to 9 hours (Supports 24W PD fast charge in 1.6 hrs)',
    },
    weight: '1.47 kg',
    officialUrl: 'https://www.zhiyun-tech.com/en/product/detail/412',
    source: 'lightbag-db',
  },
  {
    id: 'lb-gimbal-zhiyun-smooth-5s',
    category: 'gimbal',
    subcategory: 'Professional Mobile Gimbal',
    brand: 'Zhiyun',
    model: 'SMOOTH 5S',
    keySpecs: {
      structure: 'Professional 3-Axis Orthogonal Structure (360° unrestricted pan)',
      fillLight: 'Built-in 650 Lux Fill Light + 2 magnetic add-on lights',
      controlPanel: 'Round joystick, wheel adjustment, and direct phone settings',
    },
    weight: '625 g',
    officialUrl: 'https://www.zhiyun-tech.com/en/product/detail/646',
    source: 'lightbag-db',
  },
  {
    id: 'lb-gimbal-moza-air-2s',
    category: 'gimbal',
    subcategory: 'Professional DSLR Gimbal',
    brand: 'Moza',
    model: 'Air 2S',
    keySpecs: {
      testedPayload: '4.2 kg (9.3 lbs)',
      smartWheel: 'Micro handwheel for precise focus, zoom, and axis control',
      batteryLife: 'Up to 20 hours (Built-in 3200mAh high capacity)',
      powerSupply: 'Supports external power bank charging',
    },
    weight: '1.75 kg',
    officialUrl: 'https://www.gudsen.com/moza-air-2s',
    source: 'lightbag-db',
  },
  {
    id: 'lb-gimbal-feiyutech-scorp-c',
    category: 'gimbal',
    subcategory: 'Integrated Handle Camera Gimbal',
    brand: 'FeiyuTech',
    model: 'SCORP-C',
    keySpecs: {
      testedPayload: '2.5 kg',
      dualHandle: 'Integrated T-shaped and sling handle design',
      memoryTrajectory: 'A/B point button memory for automated tracking shots',
      batteryLife: 'Up to 13 hours',
    },
    weight: '1.2 kg',
    officialUrl: 'https://www.feiyu-tech.com/feiyu-scorp-c/',
    source: 'lightbag-db',
  },

  // --- DRONES ---
  {
    id: 'lb-drone-dji-mini-3',
    category: 'drone',
    subcategory: 'Sub-249g Ultralight Drone',
    brand: 'DJI',
    model: 'DJI Mini 3',
    keySpecs: {
      takeoffWeight: '< 249 g',
      sensor: '1/1.3-inch CMOS Sensor (4K HDR)',
      flightTime: 'Up to 38 minutes (51 mins with Plus battery)',
      trueVertical: 'True Vertical Camera Tilt for vertical video',
      windResistance: 'Level 5 (38 km/h)',
    },
    weight: '248 g',
    officialUrl: 'https://www.dji.com/mini-3',
    source: 'lightbag-db',
  },
  {
    id: 'lb-drone-dji-air-2s',
    category: 'drone',
    subcategory: '1-Inch Camera Drone',
    brand: 'DJI',
    model: 'DJI Air 2S',
    keySpecs: {
      sensor: '1-inch CMOS Sensor (20 MP, 2.4μm pixels)',
      videoResolution: '5.4K/30fps & 4K/60fps, 10-bit D-Log',
      obstacleSensing: '4-Directional Obstacle Sensing with APAS 4.0',
      flightTime: 'Up to 31 minutes',
      transmission: 'DJI O3 (12 km range)',
    },
    weight: '595 g',
    officialUrl: 'https://www.dji.com/air-2s',
    source: 'lightbag-db',
  },
  {
    id: 'lb-drone-dji-matrice-350-rtk',
    category: 'drone',
    subcategory: 'Enterprise Inspection Drone',
    brand: 'DJI',
    model: 'Matrice 350 RTK',
    keySpecs: {
      flightTime: 'Up to 55 minutes',
      payloadCapacity: 'Max 2.7 kg payload (Zenmuse H20N, P1, L2 lidar)',
      weatherRating: 'IP55 Weather Resistance (-20°C to 50°C)',
      transmission: 'DJI O3 Enterprise 20 km transmission',
    },
    weight: '6.47 kg',
    officialUrl: 'https://enterprise.dji.com/matrice-350-rtk',
    source: 'lightbag-db',
  },
  {
    id: 'lb-drone-autel-evo-ii-pro-v3',
    category: 'drone',
    subcategory: '6K Foldable Drone',
    brand: 'Autel Robotics',
    model: 'EVO II Pro V3',
    keySpecs: {
      sensor: '1-inch Sony CMOS (20 MP, f/2.8 - f/11 adjustable)',
      videoResolution: '6K/30fps & 4K/60fps 10-bit HDR',
      flightTime: 'Up to 40 minutes',
      obstacleAvoidance: '360° Omnidirectional Obstacle Avoidance (19 sensor groups)',
      transmission: 'SkyLink 2.0 (15 km range)',
    },
    weight: '1.19 kg',
    officialUrl: 'https://www.autelrobotics.com/productdetail/26.html',
    source: 'lightbag-db',
  },

  // --- LIGHTS ---
  {
    id: 'lb-light-aputure-amaran-cob-60d-s',
    category: 'light',
    subcategory: 'Ultra-Compact COB',
    brand: 'Aputure',
    model: 'Amaran COB 60d S',
    keySpecs: {
      type: 'Ultra-Compact Daylight Point-Source LED',
      power: '65W',
      cct: '5600K',
      cri: '96+',
      tlci: '99+',
      mount: 'Bowens Mount',
      powerOptions: 'AC Adapter, Dual NP-F970 Battery Plate, or D-Tap',
    },
    weight: '675 g',
    officialUrl: 'https://www.aputure.com/products/amaran-cob-60d-s',
    source: 'lightbag-db',
  },
  {
    id: 'lb-light-aputure-amaran-cob-60x-s',
    category: 'light',
    subcategory: 'Ultra-Compact Bi-Color COB',
    brand: 'Aputure',
    model: 'Amaran COB 60x S',
    keySpecs: {
      type: 'Ultra-Compact Bi-Color Point-Source LED',
      power: '65W',
      cct: '2700K - 6500K',
      cri: '96+',
      tlci: '97+',
      mount: 'Bowens Mount',
      powerOptions: 'AC Adapter, Dual NP-F plate, D-Tap',
    },
    weight: '675 g',
    officialUrl: 'https://www.aputure.com/products/amaran-cob-60x-s',
    source: 'lightbag-db',
  },
  {
    id: 'lb-light-nanlite-forza-150b',
    category: 'light',
    subcategory: 'Compact Bi-Color COB',
    brand: 'Nanlite',
    model: 'Forza 150B',
    keySpecs: {
      type: 'Compact Bi-Color Monolight',
      power: '170W',
      cct: '2700K - 6500K',
      cri: '96',
      tlci: '98',
      mount: 'FM Mount (Bowens Adapter included)',
      batteryOption: 'Optional V-Mount Battery Handgrip',
    },
    weight: '1.56 kg',
    officialUrl: 'https://nanliteus.com/products/forza-150b',
    source: 'lightbag-db',
  },
  {
    id: 'lb-light-godox-ad300-pro',
    category: 'light',
    subcategory: 'Battery Studio Strobe',
    brand: 'Godox',
    model: 'AD300 Pro',
    keySpecs: {
      type: 'Outdoor Monolight Strobe',
      power: '300Ws',
      recycleTime: '0.01 - 1.5s',
      cct: '5600K (±200K)',
      batteryLife: '320 Full Power Flashes (14.4V 2600mAh)',
      syncSpeed: 'HSS up to 1/8000s',
      modelingLight: '12W Bi-Color LED (3000K-6000K)',
    },
    weight: '1.25 kg (with battery)',
    officialUrl: 'https://www.godox.com/product-d/AD300Pro.html',
    source: 'lightbag-db',
  },
  {
    id: 'lb-light-godox-ad400-pro',
    category: 'light',
    subcategory: 'Battery Studio Strobe',
    brand: 'Godox',
    model: 'AD400 Pro',
    keySpecs: {
      type: 'Outdoor Monolight Strobe',
      power: '400Ws',
      recycleTime: '0.01 - 0.9s',
      batteryLife: '390 Full Power Flashes (21.6V 2600mAh)',
      syncSpeed: 'HSS up to 1/8000s',
      mount: 'Bowens Mount adapter included',
      modelingLight: '30W LED (4800K)',
    },
    weight: '2.1 kg',
    officialUrl: 'https://www.godox.com/product-d/AD400Pro.html',
    source: 'lightbag-db',
  },
  {
    id: 'lb-light-godox-v860iii',
    category: 'light',
    subcategory: 'Camera Flash Speedlight',
    brand: 'Godox',
    model: 'V860III Speedlight',
    keySpecs: {
      type: 'TTL Li-Ion On-Camera Flash',
      power: '76Ws',
      recycleTime: '1.5s',
      batteryLife: '480 Full Power Flashes (7.2V 2600mAh)',
      modelingLight: '2W Built-in front LED modeling light (10 levels)',
      quickSwitch: 'Quick switch TCM button between TTL and Manual',
    },
    weight: '530 g (with battery)',
    officialUrl: 'https://www.godox.com/product-d/V860III.html',
    source: 'lightbag-db',
  },
];

let added = 0;
for (const item of batch2) {
  if (!existingIds.has(item.id)) {
    existing.push(item);
    existingIds.add(item.id);
    added++;
  }
}

fs.writeFileSync('data/lightbag-gear-db.json', JSON.stringify(existing, null, 2), 'utf8');
console.log('Batch 2: Appended ' + added + ' items. Total items now: ' + existing.length);
