import fs from 'fs';

const existing = JSON.parse(fs.readFileSync('data/lightbag-gear-db.json', 'utf8'));
const existingIds = new Set(existing.map((i) => i.id));

const additional = [
  // --- AUDIO ---
  {
    id: 'lb-audio-rode-wireless-me',
    category: 'audio',
    subcategory: 'Wireless Microphone',
    brand: 'Rode',
    model: 'Wireless ME',
    keySpecs: {
      type: 'Compact Digital Wireless System',
      gainAssist: 'Intelligent GainAssist technology',
      dualMics: 'Built-in microphones in transmitter and receiver',
      range: 'Over 100m range',
      connectivity: 'USB-C and 3.5mm analog out',
    },
    weight: '32 g',
    officialUrl: 'https://rode.com/microphones/wireless/wireless-me',
    source: 'lightbag-db',
  },
  {
    id: 'lb-audio-rode-videomic-go-ii',
    category: 'audio',
    subcategory: 'On-Camera Shotgun',
    brand: 'Rode',
    model: 'VideoMic GO II',
    keySpecs: {
      type: 'Lightweight Directional Shotgun',
      polarPattern: 'Supercardioid',
      powerOption: 'Plug-in power or USB-C bus power',
      usbAudio: 'USB-C audio output for phones and laptops',
    },
    weight: '89 g',
    officialUrl: 'https://rode.com/microphones/on-camera/videomic-go-ii',
    source: 'lightbag-db',
  },
  {
    id: 'lb-audio-rode-videomic-pro-plus',
    category: 'audio',
    subcategory: 'On-Camera Shotgun',
    brand: 'Rode',
    model: 'VideoMic Pro+',
    keySpecs: {
      type: 'Premium On-Camera Shotgun',
      powerAuto: 'Automatic Power function with plug-in power',
      safetyChannel: 'Built-in safety channel',
      highPassFilter: '2-stage high pass filter (75Hz / 150Hz)',
    },
    weight: '122 g',
    officialUrl: 'https://rode.com/microphones/on-camera/videomic-pro-plus',
    source: 'lightbag-db',
  },
  {
    id: 'lb-audio-rode-rodecaster-pro-ii',
    category: 'audio',
    subcategory: 'Audio Production Studio',
    brand: 'Rode',
    model: 'RODECaster Pro II',
    keySpecs: {
      inputs: '4x Neutrik Combo XLR/TRS inputs with Revolution Preamps',
      dsp: 'Studio-grade APHEX audio processing',
      smartPads: '8x programmable SMART pads with bank switching',
      interfaces: 'Dual USB-C audio interfaces + Wi-Fi / Ethernet',
    },
    weight: '1.96 kg',
    officialUrl: 'https://rode.com/interfaces-and-mixers/rodecaster-series/rodecaster-pro-ii',
    source: 'lightbag-db',
  },
  {
    id: 'lb-audio-rode-rodecaster-duo',
    category: 'audio',
    subcategory: 'Compact Audio Production Studio',
    brand: 'Rode',
    model: 'RODECaster Duo',
    keySpecs: {
      inputs: '2x Neutrik Combo XLR/TRS inputs with Revolution Preamps',
      dsp: 'APHEX audio processing',
      smartPads: '6x programmable SMART pads',
      usb: 'Dual USB-C interfaces',
    },
    weight: '1.13 kg',
    officialUrl: 'https://rode.com/interfaces-and-mixers/rodecaster-series/rodecaster-duo',
    source: 'lightbag-db',
  },
  {
    id: 'lb-audio-sennheiser-mke-400',
    category: 'audio',
    subcategory: 'On-Camera Shotgun',
    brand: 'Sennheiser',
    model: 'MKE 400',
    keySpecs: {
      polarPattern: 'Supercardioid directional',
      windProtection: 'Integrated acoustic foam windscreen and internal shockmount',
      batteryLife: 'Over 100 hours on 2x AAA batteries',
      monitoring: 'Headphone monitoring output with volume control',
    },
    weight: '93.5 g',
    officialUrl: 'https://www.sennheiser.com/mke-400',
    source: 'lightbag-db',
  },
  {
    id: 'lb-audio-sennheiser-avx-me2',
    category: 'audio',
    subcategory: 'Wireless Lavalier System',
    brand: 'Sennheiser',
    model: 'AVX-ME2 SET',
    keySpecs: {
      frequency: '1.9 GHz License-Free DECT frequency range',
      autoConfig: 'Automated frequency management & dynamic range setting',
      plugInXLR: 'Ultra-compact receiver plugs directly into camera XLR',
      battery: 'Rechargeable Li-Ion battery pack',
    },
    weight: '87 g (Receiver)',
    officialUrl: 'https://www.sennheiser.com/avx-me2-set',
    source: 'lightbag-db',
  },
  {
    id: 'lb-audio-sennheiser-hd-280-pro',
    category: 'audio',
    subcategory: 'Monitoring Headphones',
    brand: 'Sennheiser',
    model: 'HD 280 Pro',
    keySpecs: {
      type: 'Closed-Back Circumaural Studio Monitor Headphones',
      attenuation: 'High ambient noise attenuation up to 32 dB',
      frequencyResponse: '8 Hz - 25,000 Hz',
      impedance: '64 Ohms',
    },
    weight: '285 g',
    officialUrl: 'https://www.sennheiser.com/hd-280-pro',
    source: 'lightbag-db',
  },
  {
    id: 'lb-audio-zoom-h1n',
    category: 'audio',
    subcategory: 'Handy Audio Recorder',
    brand: 'Zoom',
    model: 'H1n Handy Recorder',
    keySpecs: {
      mics: 'X/Y 90° Stereo Condenser Microphones',
      recording: '24-bit / 96 kHz WAV and MP3',
      batteryLife: 'Up to 10 hours on 2x AAA batteries',
      oneTouch: 'One-touch button controls and Limiter',
    },
    weight: '60 g',
    officialUrl: 'https://zoomcorp.com/en/us/handheld-recorders/handheld-recorders/h1n/',
    source: 'lightbag-db',
  },
  {
    id: 'lb-audio-zoom-h5',
    category: 'audio',
    subcategory: 'Handy Audio Recorder',
    brand: 'Zoom',
    model: 'H5 Handy Recorder',
    keySpecs: {
      inputs: '2x XLR/TRS combo inputs with analog gain knobs + interchangeable capsules',
      recording: '4-Track simultaneous recording',
      preamps: 'EIN -120 dBu low-noise preamps',
    },
    weight: '269 g',
    officialUrl: 'https://zoomcorp.com/en/us/handheld-recorders/handheld-recorders/h5/',
    source: 'lightbag-db',
  },
  {
    id: 'lb-audio-zoom-f8n-pro',
    category: 'audio',
    subcategory: 'Multi-Track Field Recorder',
    brand: 'Zoom',
    model: 'F8n Pro',
    keySpecs: {
      inputs: '8x Locking XLR/TRS Combo Inputs with 32-Bit Float dual A/D',
      tracks: '8 Inputs / 10 Tracks simultaneous recording',
      timecode: 'Accurate Timecode I/O with BNC connectors (0.2 ppm)',
    },
    weight: '1.2 kg',
    officialUrl: 'https://zoomcorp.com/en/us/field-recorders/field-recorders/f8n-pro/',
    source: 'lightbag-db',
  },
  {
    id: 'lb-audio-tascam-dr-10l',
    category: 'audio',
    subcategory: 'Digital Lavalier Recorder',
    brand: 'Tascam',
    model: 'DR-10L',
    keySpecs: {
      recording: '24-bit / 48 kHz Linear PCM with dual recording safety track',
      batteryLife: 'Up to 10 hours on a single AAA battery',
      connector: 'Screw-lock 3.5mm mic jack',
    },
    weight: '63 g',
    officialUrl: 'https://tascam.com/us/product/dr-10l/',
    source: 'lightbag-db',
  },
  {
    id: 'lb-audio-tascam-dr-40x',
    category: 'audio',
    subcategory: 'Handheld 4-Track Recorder',
    brand: 'Tascam',
    model: 'DR-40X',
    keySpecs: {
      mics: 'Adjustable Unidirectional Condenser Mics (A-B and X-Y)',
      inputs: 'Dual Locking Neutrik XLR/TRS Combo Inputs (48V Phantom)',
      audioInterface: 'USB audio interface for Mac/PC',
    },
    weight: '213 g',
    officialUrl: 'https://tascam.com/us/product/dr-40x/',
    source: 'lightbag-db',
  },
  {
    id: 'lb-audio-saramonic-blink-500-pro-b2',
    category: 'audio',
    subcategory: 'Wireless Lavalier System',
    brand: 'Saramonic',
    model: 'Blink 500 Pro B2',
    keySpecs: {
      type: 'Dual-Channel 2.4GHz Wireless System',
      oledDisplay: 'OLED display on transmitters and receiver',
      batteryLife: '8 hours per charge (Charging carry case included)',
      range: 'Up to 100m range',
    },
    weight: '32 g (Transmitter)',
    officialUrl: 'https://www.saramonic.com/product/blink500-pro-b2/',
    source: 'lightbag-db',
  },

  // --- MONITORS ---
  {
    id: 'lb-monitor-atomos-shogun-connect',
    category: 'monitor',
    subcategory: '7" HDR Cloud Monitor-Recorder',
    brand: 'Atomos',
    model: 'Shogun Connect',
    keySpecs: {
      screenSize: '7.0" 2000 nits HDR SuperAtom IPS',
      inputs: '12G-SDI & HDMI In/Out',
      cloud: 'Integrated Wi-Fi 6, Gigabit Ethernet, Frame.io Camera to Cloud',
      recordingCodec: 'Apple ProRes, Avid DNxHR, ProRes RAW up to 4Kp60',
    },
    weight: '730 g',
    officialUrl: 'https://www.atomos.com/products/shogun-connect',
    source: 'lightbag-db',
  },
  {
    id: 'lb-monitor-smallhd-ultra-5',
    category: 'monitor',
    subcategory: '5" Ultra-Bright Production Monitor',
    brand: 'SmallHD',
    model: 'Ultra 5',
    keySpecs: {
      screenSize: '5.0" Daylight Viewable Touchscreen',
      resolution: '1920 x 1080',
      brightness: '3000 nits',
      inputs: '3G-SDI & HDMI 2.0 In/Out',
      weatherproof: 'IP54 Weather Resistant Housing',
    },
    weight: '490 g',
    officialUrl: 'https://link.smallhd.com/ultra5',
    source: 'lightbag-db',
  },
  {
    id: 'lb-monitor-smallhd-cine-5',
    category: 'monitor',
    subcategory: '5" Cine Touchscreen Monitor',
    brand: 'SmallHD',
    model: 'Cine 5',
    keySpecs: {
      screenSize: '5.0" DCI-P3 Color Gamut Display',
      resolution: '1920 x 1080',
      brightness: '2000 nits',
      inputs: '3G-SDI & HDMI In/Out',
      chassis: 'Milled Unibody Aluminum',
    },
    weight: '440 g',
    officialUrl: 'https://link.smallhd.com/cine5',
    source: 'lightbag-db',
  },
  {
    id: 'lb-monitor-smallhd-action-5',
    category: 'monitor',
    subcategory: '5" Compact Lightweight Monitor',
    brand: 'SmallHD',
    model: 'Action 5',
    keySpecs: {
      screenSize: '5.2" LCD Touchscreen',
      resolution: '1920 x 1080',
      brightness: '2000 nits',
      inputs: 'HDMI In/Out (No SDI)',
      weight: '240 g ultra-lightweight',
    },
    weight: '240 g',
    officialUrl: 'https://link.smallhd.com/action5',
    source: 'lightbag-db',
  },
  {
    id: 'lb-monitor-blackmagic-video-assist-7-12g',
    category: 'monitor',
    subcategory: '7" 12G-SDI / HDMI HDR Recorder',
    brand: 'Blackmagic Design',
    model: 'Video Assist 7" 12G HDR',
    keySpecs: {
      screenSize: '7.0" 2500 nits HDR Touchscreen',
      resolution: '1920 x 1200',
      inputs: '12G-SDI & HDMI 2.0 + Mini XLR analog audio with phantom power',
      recordingCodec: 'Blackmagic RAW, ProRes, DNxHD to dual SD card slots & USB-C',
    },
    weight: '825 g',
    officialUrl: 'https://www.blackmagicdesign.com/products/blackmagicvideoassist',
    source: 'lightbag-db',
  },
  {
    id: 'lb-monitor-portkeys-bm5-iii-wr',
    category: 'monitor',
    subcategory: '5.5" Camera Control Monitor',
    brand: 'Portkeys',
    model: 'BM5 III WR',
    keySpecs: {
      screenSize: '5.5" 2200 nits High Bright Display',
      cameraControl: 'Wireless Camera Control for RED Komodo/V-Raptor and Sony FX3/A7M4',
      inputs: 'SDI & HDMI In/Out with Cross Conversion',
    },
    weight: '376 g',
    officialUrl: 'https://www.portkeys.com/bm5-iii-wr/',
    source: 'lightbag-db',
  },
  {
    id: 'lb-monitor-feelworld-f6-plus-v2',
    category: 'monitor',
    subcategory: '6" 3D LUT Field Monitor',
    brand: 'Feelworld',
    model: 'F6 Plus V2',
    keySpecs: {
      screenSize: '6.0" IPS Touchscreen',
      resolution: '1920 x 1080',
      brightness: '500 nits',
      inputs: '4K HDMI In/Out, Type-C 5V DC In & 3D LUT support',
    },
    weight: '235 g',
    officialUrl: 'https://feelworld.ltd/products/feelworld-f6-plus-v2',
    source: 'lightbag-db',
  },
  {
    id: 'lb-monitor-accsoon-seemo-pro',
    category: 'monitor',
    subcategory: 'SDI / HDMI iOS Video Adapter',
    brand: 'Accsoon',
    model: 'SeeMo Pro SDI/HDMI',
    keySpecs: {
      type: 'Broadcast SDI/HDMI to iOS Camera Monitor Adapter',
      inputs: 'HD-SDI In/Out Loop & HDMI In',
      power: 'NP-F Battery or 2-Pin LEMO DC',
      audio: '3.5mm Headphone Jack',
    },
    weight: '220 g',
    officialUrl: 'https://accsoon.com/seemo-pro/',
    source: 'lightbag-db',
  },
  {
    id: 'lb-monitor-hollyland-mars-4k',
    category: 'monitor',
    subcategory: '4K Wireless Video Transmitter',
    brand: 'Hollyland',
    model: 'Mars 4K Wireless Video System',
    keySpecs: {
      resolution: '4K/30fps Video Transmission',
      range: 'Up to 150m (450 ft) Line of Sight',
      latency: 'Ultra-low 66 ms latency',
      inputs: 'HDMI & SDI In/Out',
    },
    weight: '223 g',
    officialUrl: 'https://www.hollyland.com/product/mars-4k',
    source: 'lightbag-db',
  },

  // --- TRIPODS ---
  {
    id: 'lb-tripod-manfrotto-190xpro4',
    category: 'tripod',
    subcategory: 'Photo Tripod Legs',
    brand: 'Manfrotto',
    model: '190XPRO4 Aluminum 4-Section Tripod',
    keySpecs: {
      material: 'Aluminum',
      maxHeight: '160 cm',
      foldedLength: '49 cm',
      maxLoad: '7.0 kg',
      column: '90° Center Column for macro/ground shots',
    },
    weight: '2.05 kg',
    officialUrl: 'https://www.manfrotto.com/global-en/190xpro4-aluminium-4-section-photo-tripod-mt190xpro4/',
    source: 'lightbag-db',
  },
  {
    id: 'lb-tripod-sachtler-ace-xl',
    category: 'tripod',
    subcategory: 'Video Fluid Head Tripod',
    brand: 'Sachtler',
    model: 'Ace XL Carbon Fiber System',
    keySpecs: {
      maxLoad: '2 - 8 kg',
      head: 'Ace XL 75mm Fluid Head with 8-step counterbalance',
      maxHeight: '173 cm',
      foldedLength: '86 cm',
    },
    weight: '4.1 kg',
    officialUrl: 'https://www.sachtler.com/en/products/system-ace-xl-ft-75/',
    source: 'lightbag-db',
  },
  {
    id: 'lb-tripod-benro-rhino-24c',
    category: 'tripod',
    subcategory: 'Carbon Fiber Travel Tripod',
    brand: 'Benro',
    model: 'Rhino 24C + VX25 Ball Head',
    keySpecs: {
      material: 'Carbon Fiber',
      maxHeight: '168.5 cm',
      foldedLength: '49 cm',
      maxLoad: '18 kg',
      monopodConvertible: 'Leg detaches to convert to full-size monopod',
    },
    weight: '1.74 kg',
    officialUrl: 'https://benroeu.com/benro-rhino-series-tripods/',
    source: 'lightbag-db',
  },
  {
    id: 'lb-tripod-gitzo-traveler-series-1',
    category: 'tripod',
    subcategory: 'Luxury Carbon Travel Tripod',
    brand: 'Gitzo',
    model: 'Traveler Series 1 Carbon eXact (GT1545T)',
    keySpecs: {
      material: 'Carbon eXact Tubing',
      maxHeight: '153 cm',
      foldedLength: '42.5 cm (180° leg folding)',
      maxLoad: '10 kg',
      locking: 'G-Lock Ultra Twist Locks',
    },
    weight: '1.06 kg',
    officialUrl: 'https://www.gitzo.com/global-en/traveler-tripod-series-1-carbon-4-sections-gt1545t/',
    source: 'lightbag-db',
  },
  {
    id: 'lb-tripod-smallrig-ad-01-heavy-duty',
    category: 'tripod',
    subcategory: 'Heavy-Duty Video Tripod',
    brand: 'SmallRig',
    model: 'Heavy-Duty Aluminum Video Tripod AD-01',
    keySpecs: {
      material: 'Aluminum Dual-Tube',
      maxHeight: '186 cm',
      foldedLength: '89 cm',
      maxLoad: '8.0 kg',
      head: 'Fluid damping head with quick-release plate for DJI RS 2 / RS 3 / RS 4',
    },
    weight: '4.0 kg',
    officialUrl: 'https://www.smallrig.com/SmallRig-Heavy-Duty-Fluid-Head-Tripod-AD-01-3751.html',
    source: 'lightbag-db',
  },

  // --- GIMBALS ---
  {
    id: 'lb-gimbal-dji-rs-3-pro',
    category: 'gimbal',
    subcategory: 'Cinema Camera Gimbal',
    brand: 'DJI',
    model: 'DJI RS 3 Pro',
    keySpecs: {
      testedPayload: '4.5 kg (10 lbs) Carbon Fiber Arms',
      automatedAxisLocks: 'Automated 1st-Gen Axis Locks',
      lidarFocus: 'Supports DJI LiDAR Range Finder (RS)',
      batteryLife: 'Up to 12 hours',
    },
    weight: '1.5 kg',
    officialUrl: 'https://www.dji.com/rs-3-pro',
    source: 'lightbag-db',
  },
  {
    id: 'lb-gimbal-dji-rs-3',
    category: 'gimbal',
    subcategory: '3-Axis Camera Gimbal',
    brand: 'DJI',
    model: 'DJI RS 3',
    keySpecs: {
      testedPayload: '3.0 kg (6.6 lbs)',
      automatedAxisLocks: 'Automated Axis Locks',
      screen: '1.8" OLED Full-Color Touchscreen',
      batteryLife: 'Up to 12 hours',
    },
    weight: '990 g',
    officialUrl: 'https://www.dji.com/rs-3',
    source: 'lightbag-db',
  },
  {
    id: 'lb-gimbal-zhiyun-crane-m2s',
    category: 'gimbal',
    subcategory: 'Compact Multi-Device Gimbal',
    brand: 'Zhiyun',
    model: 'CRANE-M2 S',
    keySpecs: {
      compatibility: 'Action cams, smartphones, light mirrorless',
      fillLight: 'Built-in 1000 Lumens Fill Light',
      batteryLife: 'Up to 10.5 hours with quick charge',
    },
    weight: '549 g',
    officialUrl: 'https://www.zhiyun-tech.com/en/product/detail/553',
    source: 'lightbag-db',
  },
  {
    id: 'lb-gimbal-moza-aircross-3',
    category: 'gimbal',
    subcategory: 'Transformable 3-Axis Gimbal',
    brand: 'Moza',
    model: 'AirCross 3',
    keySpecs: {
      testedPayload: '3.2 kg (7 lbs)',
      foldableDesign: '4 Transformable Configurations (Classic, Sling, Dual-Hand, Vertical)',
      batteryLife: 'Up to 19 hours',
    },
    weight: '1.3 kg',
    officialUrl: 'https://www.gudsen.com/moza-aircross-3',
    source: 'lightbag-db',
  },

  // --- DRONES ---
  {
    id: 'lb-drone-dji-mini-3-pro',
    category: 'drone',
    subcategory: 'Sub-249g Camera Drone',
    brand: 'DJI',
    model: 'DJI Mini 3 Pro',
    keySpecs: {
      takeoffWeight: '< 249 g',
      sensor: '1/1.3-inch CMOS Sensor (48 MP, f/1.7)',
      videoResolution: '4K/60fps HDR, 10-bit D-Cinelike',
      obstacleSensing: 'Tri-Directional Obstacle Sensing (Forward/Backward/Downward)',
      flightTime: 'Up to 34 minutes (47 mins with Plus battery)',
      trueVertical: 'True Vertical Shooting (rotatable camera)',
    },
    weight: '249 g',
    officialUrl: 'https://www.dji.com/mini-3-pro',
    source: 'lightbag-db',
  },
  {
    id: 'lb-drone-dji-mavic-3-cine',
    category: 'drone',
    subcategory: 'Apple ProRes Cine Drone',
    brand: 'DJI',
    model: 'DJI Mavic 3 Cine',
    keySpecs: {
      sensor: '4/3 Hasselblad + 1/2 Tele Camera',
      videoResolution: '5.1K Apple ProRes 422 HQ / 4K 120fps',
      internalStorage: 'Built-in 1TB High-Speed SSD',
      flightTime: 'Up to 46 minutes',
    },
    weight: '899 g',
    officialUrl: 'https://www.dji.com/mavic-3',
    source: 'lightbag-db',
  },
  {
    id: 'lb-drone-dji-fpv',
    category: 'drone',
    subcategory: 'First-Person View Drone',
    brand: 'DJI',
    model: 'DJI FPV',
    keySpecs: {
      speed: 'Up to 140 km/h (87 mph) in Manual Mode (0-100 km/h in 2.0s)',
      camera: '4K/60fps 150° Super-Wide Angle Camera',
      transmission: 'DJI O3 HD Low-Latency Video Transmission with Goggles V2',
      emergencyBrake: 'Emergency Brake and Hover button',
    },
    weight: '795 g',
    officialUrl: 'https://www.dji.com/dji-fpv',
    source: 'lightbag-db',
  },
  {
    id: 'lb-drone-hoverair-x1-promax',
    category: 'drone',
    subcategory: '8K Flying Action Camera',
    brand: 'HoverAir',
    model: 'HoverAir X1 PROMAX',
    keySpecs: {
      weight: '192 g',
      videoResolution: '8K/30fps & 4K/120fps with 10-bit HLG',
      sensor: '1/1.3-inch Custom CMOS Sensor',
      followSpeed: 'Up to 42 km/h (26 mph) tracking on snow and water',
      flightTime: 'Up to 16 minutes',
    },
    weight: '192 g',
    officialUrl: 'https://hoverair.com/products/hoverair-x1-promax',
    source: 'lightbag-db',
  },
];

let added = 0;
for (const item of additional) {
  if (!existingIds.has(item.id)) {
    existing.push(item);
    existingIds.add(item.id);
    added++;
  }
}

fs.writeFileSync('data/lightbag-gear-db.json', JSON.stringify(existing, null, 2), 'utf8');
console.log('Appended ' + added + ' items. Total items now: ' + existing.length);
